name: Java CI with Maven

on:
  push:
    branches:
      
main
pull_request:
  branches:
main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
name: Checkout repository
    uses: actions/checkout@v4  # Atualize para a última versão disponível

    
name: Set up JDK 11
    uses: actions/setup-java@v4  # Atualize para a última versão disponível
    with:
      java-version: '11'
      distribution: 'adopt'

    
name: Cache Maven dependencies
    uses: actions/cache@v4  # Atualize para a última versão disponível
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      restore-keys: |${{ runner.os }}-maven

    
name: Build with Maven
    run: mvn clean install

    
name: Run tests
    run: mvn test
